### ISSUE TITLE
feature request: make setConvexClientContext public

### ISSUE THREAD

**Issue by NotWoods** [get-convex/convex-svelte#5]
For SvelteKit, I want to be able to share a Convex Client between load functions and my .svelte files. This is possible in convex-react/Remix because the client is created separately then passed to ConvexClientProvider. 

setConvexClientContext is the nearest equivalent in Svelte land and it's already present in the client file. It would be great if the function was exported too!

**Comment by keithkelly31** [comment]
@NotWoods Do you want to share the client between server load functions (+page.server.ts) or browser load functions (+page.ts)?

**Comment by NotWoods** [comment]
I'm looking to share it between client load function (+page.ts) and .svelte files

**Comment by thomasballinger** [comment]
You got it! Is there you want here @NotWoods? Or should setupConvex take a client as an argument, and not close in a cleanup effect if it was passed in?

**Comment by thomasballinger** [comment]
done in https://github.com/get-convex/convex-svelte/pull/16, @NotWoods lmk if there's a different API you'd prefer
